# Generated by Django 3.2.5 on 2021-11-08 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('open', models.TimeField()),
                ('close', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('enrolment', models.CharField(max_length=25, unique=True)),
                ('c_lass', models.CharField(db_column='class', max_length=100, null=True)),
                ('training', models.BooleanField(default=False)),
                ('photos', models.IntegerField(default=0)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.shift')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Totem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_address', models.CharField(max_length=12, unique=True)),
                ('ip', models.CharField(max_length=15)),
                ('student', models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='web.student')),
            ],
        ),
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.student')),
                ('totem', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='web.totem')),
            ],
        ),
    ]
